### ISSUE TITLE
refactor: variables aren't sorted logically

### ISSUE THREAD

**Issue by karlnippoldt** [lauthieb/variables-converter-figma-plugin#4]
It appears that the variables are sorted by the order in which they were originally created, which isn't really useful. It would be helpful to keep them sorted in the same order they're set to in Figma Design mode, or alternately alphabetical order so it's at least easier to find a variable when you're looking for it.

**Comment by lauthieb** [comment]
Hi @karlnippoldt,
Thanks for your proposition! You're right! I think alphabetically is the best 👌🏻

**Comment by lauthieb** [comment]
That's done thanks to this commit: https://github.com/lauthieb/variables-converter-figma-plugin/commit/d41c248a12e40d67d3fe72ff3de329123bdbb2d6

**Before:**
<img width="331" alt="CleanShot 2023-07-04 at 22 39 36@2x" src="https://github.com/lauthieb/variables-converter-figma-plugin/assets/9600228/3bd3220c-3fc4-403a-890c-b2352bb10dc3">

**After:**
<img width="330" alt="CleanShot 2023-07-04 at 22 39 45@2x" src="https://github.com/lauthieb/variables-converter-figma-plugin/assets/9600228/345bf10a-629a-42d7-b038-2dcc341a1403">

It is now in production in the latest version (https://www.figma.com/community/plugin/1256000104406722117) 🎉 

<img width="534" alt="CleanShot 2023-07-04 at 22 41 11@2x" src="https://github.com/lauthieb/variables-converter-figma-plugin/assets/9600228/ae7edfbd-deb6-4f5c-96a5-c5fa726b62a2">

Thank you again @karlnippoldt for your idea.
